	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
	<meta name="description" content="the homepage of lenrinfvck" >
	<meta name="author" content="lenrinfvck.cn" >
	<meta name="keywords" content="lenrinfvck mad NTRF mader LRF 个人主页" >
	<link rel="shortcut icon" href="logo.ico" />
  	<link type="text/css" href="CSS/lrfmad.css" rel="stylesheet" />
  	<link type="text/css" href="CSS/lside.css" rel="stylesheet" />
  	<style>
  	</style>
  	<script src="time.js"></script>
 	<script src="imagepre.js"></script>